Added PHP 8.0 support #4
mezzio/mezzio-helpers pull request #5
Opened 2020-11-04 12:52 UTC by svycka

Q | A
-- | --
New Feature | yes

Summary
To be prepared for the december release of PHP 8.0, this repository has some additional TODOs to be tested against the new major version.

In order to make this repository compatible, one has to follow these steps:

- [x] Modify composer.json to provide support for PHP 8.0 by adding the constraint ~8.0.0
- [x] Modify composer.json to drop support for PHP less than 7.3
- [x] Modify composer.json to implement phpunit 9.3 which supports PHP 7.3+
- [x] Modify .travis.yml to ignore platform requirements when installing composer dependencies (simply add --ignore-platform-reqs to COMPOSER_ARGS env variable)
- [x] Modify .travis.yml to add PHP 8.0 to the matrix (NOTE: Do not allow failures as PHP 8.0 has a feature freeze since 2020-08-04!)
- [x] Modify source code in case there are incompatibilities with PHP 8.0

2020-11-05 05:50 UTC, samsonasik commented on test/BodyParams/BodyParamsMiddlewareTest.php
> +use ReflectionProperty;
can be moved after line 23 directly

2020-11-05 08:09 UTC, froschdesign requested changes
Thanks for your contribution! 👍 

This is a first review with some small hints.

2020-11-05 08:09 UTC, froschdesign commented on .travis.yml
> +    - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
The new parameter is only needed for the nightly version. Please move this to the related section.

2020-11-05 08:09 UTC, froschdesign commented on .travis.yml
>          - DEPS=lowest
```suggestion
    - php: nightly
      env:
        - DEPS=lowest
        - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
```

2020-11-05 08:09 UTC, froschdesign commented on .travis.yml
>          - DEPS=latest
```suggestion
    - php: nightly
      env:
        - DEPS=latest
        - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
```

2020-11-05 08:09 UTC, froschdesign commented on phpunit.xml.dist
> +<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd" bootstrap="vendor/autoload.php" colors="true">
The local XML schema definition can be used here:
```suggestion
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd" bootstrap="vendor/autoload.php" colors="true">
```

2020-11-17 21:51 UTC, boesing approved these changes
LGTM

2020-11-18 02:41 UTC, samsonasik approved these changes

2020-11-18 13:56 UTC, merged

2020-11-18 13:56 UTC, boesing commented
Thanks, @svycka!